config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, module: "admins"
  devise_for :customers, module: "customers"

  #以下、public関連のコントローラー/アクション関係設定

  root 'homes#top'
  get 'homes/about' => 'public/homes#about'

  namespace :public do

  resources :items, only: [:index, :show]

  resources :customers, only: [:show, :edit, :update]do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
    end
  end

  resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      post 'confirm'
      get 'complete'
    end
  end

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  #以下、admin関連のコントローラー/アクション設定

  namespace :admin do
  get '/', to: 'homes#top'

  resources :items, only: [:index, :new, :create, :show, :edit, :update]

  resources :genres, only: [:index, :create, :edit, :update]

  resources :customers, only: [:index, :show, :edit, :update]

  get 'admin/orders/:id' =>'orders#show' ,  as: "admin_orders"
  patch 'admin/orders/:id' =>'orders#update'
  patch 'admin/order_details/:id' =>'order_details#update' , as: "admin_order_details"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders
  
  def active_for_authentication?
    super && (validation == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

 def index
  @customers = Customer.all
  @customers = Customer.page(params[:page]).per(10)
 end

 def show
  @customer = Customer.find(params[:id])
 end

 def edit
  @customer = Customer.find(params[:id])
 end

 def update
  @customer = Customer.find(params[:id])
  if @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  else
    render :edit
  end
 end

 private

 def customer_params
  params.require(:customer).permit(:last_name, :first_name, :kata_last_name, :kata_first_name, :postal_code, :address, :telephone_number, :email, :validation )
 end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  
  def reject_user
    @customer = Customer.find_by(name: params[:customer][:last_name][:first_name])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == false)
        redirect_to new_customer_registration_path
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end
  

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

  <div class="row">
    <h5><%= "#{@customer.last_name} #{@customer.first_name}"%>さんの情報</h5>
  </div>

  <div class="row">
    <%= form_for(@customer, url: admin_customer_path(@customer), class:"form-horizontal") do |f| %>
      <div class="col-md-12">
        <table class="customertable2">
          <tbody>
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id%></td>
            </tr>
             <tr>
              <td>氏名</td>
              <td><%= f.text_field :last_name, class: "form-control" %></td>
              <td><%= f.text_field :first_name, class: "form-control" %></td>
            </tr>
            <tr>
              <td>フリガナ</td>
              <td><%= f.text_field :kata_last_name, class: "form-control" %></td>
              <td><%= f.text_field :kata_first_name, class: "form-control" %></td>
            </tr>
            <tr>
              <td>郵便番号</td>
              <td><%= f.text_field :postal_code, class: "form-control" %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td><%= f.text_field :address, class: "form-control" %></td>
            </tr>
            <tr>
              <td>電話番号</td>
              <td><%= f.text_field :telephone_number, class: "form-control" %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td><%= f.email_field :email, autocomplete: "email", class: "form-control" %></td>
            </tr>
            <tr>
              <td>会員ステータス</td>
              <td>
                <%= f.radio_button :validation, false %>
                <%= f.label :validation, "有効", value: true %>
              </td>
              <td>
                <%= f.radio_button :validation, true %>
                <%= f.label :validation, "退会", value: false %>
              </td>
            </tr>
            <tr>
              <td><%= f.submit "変更を保存", class:"btn btn-success mt-3 offset-md-10" %></td>
            </tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h4>会員一覧</h4>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="customertable">
        <thead>
           <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>         
        </thead>
        <tdody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.last_name+customer.first_name, admin_customer_path(customer.id) %></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.validation == false %>
									<%= "有効" %>
								    <% else %>
									<%= "退会" %>
								<% end %>
							</td>
            </tr>
            <% end %>
        </tdody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h3><%= "#{@customer.last_name} #{@customer.first_name}" %>さんの情報</h3>
      <div class="col-md-12">
        <table class="customertable">
          <tbody>
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id%></td>
            </tr>
             <tr>
              <td>氏名</td>
              <td><%= "#{@customer.last_name} #{@customer.first_name}" %></td>
            </tr>
            <tr>
              <td>フリガナ</td>
              <td><%= "#{@customer.kata_last_name} #{@customer.kata_first_name}" %></td>
            </tr>
            <tr>
              <td>郵便番号</td>
              <td><%= @customer.postal_code %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td><%= @customer.address %></td>
            </tr>
            <tr>
              <td>電話番号</td>
              <td><%= @customer.telephone_number %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td><%= @customer.email %></td>
            </tr>
            <tr>
              <td>会員ステータス</td>
              <td>
                <% if @customer.validation == false %>
                  有効
                <% else %>
                  退会
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  <div class="row">
    <div class="col-md-10 offset-md-2">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success canceltab1" %>
      <%= link_to "注文履歴一覧を見る", admin_admin_orders_path(customer_id: @customer.id), class: "btn btn-primary" %>
    </div>
  </div>
</div>