config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, module: "admins"
  devise_for :customers, module: "customers"

  #以下、public関連のコントローラー/アクション関係設定

  root 'homes#top'
  get 'homes/about' => 'public/homes#about'

  namespace :public do

  resources :items, only: [:index, :show]

  resources :customers, only: [:show, :edit, :update]do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
    end
  end

  resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      post 'confirm'
      get 'complete'
    end
  end

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  #以下、admin関連のコントローラー/アクション設定

  namespace :admin do
  get '/', to: 'homes#top'

  resources :items, only: [:index, :new, :create, :show, :edit, :update]

  resources :genres, only: [:index, :create, :edit, :update]

  resources :customers, only: [:index, :show, :edit, :update]

  get 'admin/orders/:id' =>'orders#show' ,  as: "admin_orders"
  patch 'admin/orders/:id' =>'orders#update'
  patch 'admin/order_details/:id' =>'order_details#update' , as: "admin_order_details"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

 belongs_to :customer

 def full_address
  '〒' + postal_code + ' ' + addresses + ' ' + name
 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders
  
  def active_for_authentication?
    super && (validation == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  attachment :image
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def total price
    ((price * 1.1).floor) * amount
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { unpaid: 0 , paid: 1, making: 2, ready: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { impossible: 0, waiting: 1, making: 2, finish: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

before_action :authenticate_admin!

def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  @genre =Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
    redirect_to admin_genres_path
  else
    render :edit
  end
end

private

def genre_params
  params.require(:genre).permit(:name, :validation)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
    @order_details = OrderDetail.all
    @orders = Order.page(params[:page]).reverse_order.per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :validation)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
    @order_details = OrderDetail.all
    @orders = Order.page(params[:page]).reverse_order.per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.all
  end

  def update
    @orders= Order.find(params[:id])
    @orders.update(order_params)
    redirect_to admin_admin_orders_path
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_customer
      root_path
    else
      admin_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :kata_first_name, :kata_last_name, :email, :postal_code, :address, :telephone_number ])
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: :top

  def top
    @items = Item.page(params[:page]).per(4)
    @genres = Genre.all
  end

def about

end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="title_genre">ジャンル追加・一覧</h3>
    </div>
      <div class="row">
        <div class="col-md-12 mt-5">
          <div class="form-group form-horizontal">
            <%= form_for(@genre, url: admin_genre_path(@genre.id)) do |f| %>
              <%= f.label :name, "ジャンル", class: "genre_name"  %>
              <%= f.text_field :name, autofocus: true %>
              <%= f.submit "変更を保存する", class: "btn btn-success genre_registration" %>
          </div>
        </div>
        <% end %>
      </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="title_genre">ジャンル追加・一覧</h3>
    </div>
  </div>

      <div class="row">
        <div class="col-md-12 mb-5">
          <div class="form-group form-horizontal">
            <%= form_for(@genre, url: admin_genres_path) do |f| %>
            <tr>
              <td><%= f.label :name, "ジャンル", class: "genre_name" %></td>
              <td><%= f.text_field :name, autofocus: true %></td>
              <td><%= f.submit "新規登録", class: "btn btn-success genre_registration" %></td>
            </tr>
          </div>
        </div>
        <% end %>
      </div>

        <div class="row">
          <div class="col-md-4">
            <table class="table">
              <tr>
                <th class="mt-5">ジャンル</th>
              </tr>
                <% @genres.each do |genre| %>
                <tr>
                  <td><%= genre.name %></td>
                  <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <h2>商品編集</h2>
  <%= form_for(@item, url:admin_item_path(@item.id)) do |f| %>
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-3">
            <div class="field mt-5">
              <div class="form-group">
              </div>
            </div>
            <div class="img-fluid">
              <div class="form-group">
                <%= f.label :image, "商品画像" %>
              </div>
            </div>
            <div class="field name-left">
              <div class="form-group">
                <%= f.label :name, "商品名" %>
              </div>
            </div>
            <div class="field name-left">
              <div class="form-group">
                <%= f.label :introduction, "商品説明" %>
              </div>
            </div>
            <div class="field name-left">
              <div class="form-group">
                <%= f.label :genre, "ジャンル" %>
              </div>
            </div>
            <div class="field name-left">
              <div class="form-group">
                <%= f.label :price, "税抜価格" %>
              </div>
            </div>
            <div class="field name-left">
              <div class="form-group">
                <%= f.label :validation, "販売ステータス" %>
              </div>
            </div>
          </div>
          <div class="col-md-9">
            <div class="field mt-5">
              <div class="form-group">
                <div class= "col-md-1"></div>
                <div class= "img-fluid col-md-8">
                  <%= f.attachment_field :image %>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class= "col-md-1"></div>
              <div class= "col-md-7">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
            <div class="form-group name-left">
              <div class= "col-md-1"></div>
              <div class= "col-md-7">
                <%= f.text_field :introduction, class: "form-control" %>
              </div>
            </div>
            <div class="form-group name-left">
              <div class= "col-md-1"></div>
              <div class= "col-md-7">
                <%= f.collection_select :genre_id, Genre.all, :id, :name, class: "form-control" %>
              </div>
            </div>
            <div class="form-group name-left">
              <div class= "col-md-1"></div>
              <div class= "col-md-7">
                <%= f.text_field :price %>円
              </div>
            </div>

            <div class="form-group name-left">
              <div class= "col-md-1"></div>
              <div class= "col-md-7">
                <%= f.select :validation, {
                  "販売中": true,
                  "販売停止中": false
                } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-7">
        <%= f.submit "変更を保存", class: "btn btn-success mx-auto d-block" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
		<h1>商品一覧</h1>
			<div class="text-right">
				<%= link_to "+", new_admin_item_path, class: " btn btn-default", style: "border-radius: 50%" %>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<table class="table table-hover table-resposive">
				<thead>
					<tr>
						<th>商品ID</th>
						<th>商品名</th>
						<th>税込価格</th>
						<th>ジャンル</th>
						<th>ステータス</th>
					</tr>
				</thead>
				<tbody>
					<% @items.each do |item| %>
						<tr>
							<td><%= item.id %></td>
							<td><%= link_to item.name, admin_item_path(item.id) %></td>
							<td><%= (item.price*1.1).floor %></td>
							<td><%= item.genre.name %>
							</td>
							<td>
								<% if item.validation == true %>
									<%= "販売中"%>
								<% else %>
									<%= "売り切れ" %>
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>

	<div class="row">
		<div class="mx-auto">
			<%= paginate @items %>
		</div>
	</div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h2>商品新規登録</h2>
  <%= form_for(@item, url: admin_items_path) do |f| %>
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-3">
              <div class="field mt-5">
                <div class="form-group">
                </div>
              </div>
              
        <div class="img-fluid">
          <div class="form-group">
            <%= f.label :image, "商品画像" %>
          </div>
        </div>

        <div class="field name-left">
          <div class="form-group">
            <%= f.label :name, "商品名" %>
          </div>
        </div>

        <div class="field name-left">
          <div class="form-group">
            <%= f.label :introduction, "商品説明" %>
          </div>
        </div>

        <div class="field name-left">
          <div class="form-group">
            <%= f.label :genre, "ジャンル" %>
          </div>
        </div>

        <div class="field name-left">
          <div class="form-group">
            <%= f.label :price, "税抜価格" %>
          </div>
        </div>

        <div class="field name-left">
          <div class="form-group">
            <%= f.label :validation, "販売ステータス" %>
          </div>
        </div>
      </div>

     <div class="col-md-9">
      <div class="field mt-5">
        <div class="form-group">
          <div class= "col-md-1"></div>
          <div class= "img-fluid col-md-8">
            <%= f.attachment_field :image %>
          </div>
          </div>
        </div>

          <div class="form-group">
        <div class= "col-md-1"></div>
          <div class= "col-md-7">
            <%= f.text_field :name, placeholder: '商品名', class: "form-control" %>
          </div>
        </div>

      <div class="form-group name-left">
        <div class= "col-md-1"></div>
          <div class= "col-md-7">
            <%= f.text_field :introduction, placeholder: 'ここに説明文を記述します', class: "form-control" %>
        </div>
      </div>

      <div class="form-group name-left">
        <div class= "col-md-1"></div>
          <div class= "col-md-7">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, class: "form-control" %>
          </div>
        </div>

      <div class="form-group name-left">
        <div class= "col-md-1"></div>
          <div class= "col-md-7">
            <%= f.text_field :price, placeholder: '1000' %>円
        </div>
      </div>

      <div class="form-group">
        <div class= "col-md-1"></div>
          <div class= "col-md-7">
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
              <label class="form-check-label" for="inlineRadio1">販売中</label>
            </div>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="inlineRadioOptions"  id="inlineRadio2" value="option2">
              <label class="form-check-label" for="inlineRadio2">販売停止中</label>
            </div>
        </div>
      </div>
      </div>
      </div>
    </div>
    </div>
    <div class="row">
      <div class="col-md-7">
        <%= f.submit "新規登録", class: "btn btn-success mx-auto d-block" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= attachment_image_tag @item, :image, format: "jpg", fallback: "logo.png", size: "250x250" %>
    </div>
    <div class="col-md-8">
      <table class="itemtable">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <td></td>
          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <td></td>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <td></td>
          <tr>
            <td>税込価格(税抜価格)</td>
            <td><%= (@item.price*1.1).floor %> (<%= @item.price %>)円</td>
          </tr>
          <td></td>
          <tr>
            <td>販売ステータス</td>
            <td>
              <% if @item.validation == true%>
                販売中
                <% else %>
                  売り切れ
                <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

    <div class="row">
      <div class="mx-auto">
        <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success", style: "margin: 20px" %>
      </div>
    </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4>注文履歴一覧</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to admin_admin_orders_path(order.id) do %><%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %><% end %></td>
              <td><%= order.customer.last_name %> <%= order.customer.first_name %></td>
                <% @num =0 %>
              <td>
                <% order.order_details.each do |order_detail| %>
                <% @num += order_detail.amount %>
                <% end %>
                <%= @num %>
              </td>
              <td><%= order.status_i18n %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
		<div class="col-md-4 col-md-offset-4">
			  <div class="mx-auto">
				  <%= paginate @orders %>
			  </div>
		  </div>
	  </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-4 col-md-offset-2">
     <h3>注文履歴詳細</h3>
   </div>
  </div>
   <div class="row">
    <div class="col-md-7">
        <table class="table">
          <tbody>
            <tr>
             <td>購入者</td>
             <td><%= @order.customer.last_name %> <%= @order.customer.first_name %></td>
            </tr>
            <tr>
              <td>注文日</td>
              <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
            <tr>
              <td>配送先</td>
                <td>
                  <%= @order.postal_code %>
                  <%= @order.address %><br/>
                  <%= @order.name %>
                </td>
            </tr>
            <tr>
              <td>支払方法</td>
              <td><%= @order.payment_method_i18n %></td>
            </tr>
            <tr>
              <td>注文ステータス</td>
              <%= form_with model:@order, url: admin_admin_orders_path(@order.id), local:true do |f| %>
              <td><%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %></td>
              <td><%= f.submit "更新", class: "btn btn-success" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
    </div>
      <div class="col-md-9">
        <h4>請求情報</h4>
          <table class="table table-hoever table-bordered">
            <thead>
              <tr>
                <th>商品名</th>
                <th>単価(税込)</th>
                <th>数量</th>
                <th>小計</th>
                <th>製作ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @order.order_details.each do |order_detail| %>
              <tr>
                <td><%= order_detail.item.name %></td>
                <td><%= order_detail.item.with_tax_price %></td>
                <td><%= order_detail.amount %></td>
                <td><%= (((order_detail.price) * (order_detail.amount)) * 1.1).floor %></td>
                <%= form_with model:order_detail, url: admin_admin_order_details_path(order_detail.id), local:true do |f| %>
                <td><%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %></td>
                <td><%= f.submit "更新", class: "btn btn-success" %></td>
                <% end %>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="col-md-3">
          <table class="table">
            <tbody>
              <tr>
                <td>商品合計</td>
                  <% @num =0 %>
                <td>
                  <% @order.order_details.each do |order_detail| %>
                  <% @num += (((order_detail.price) * 1.1 * (order_detail.amount))).floor %>
                  <% end %>
                  <%= @num %>円
                </td>
              </tr>
              <tr>
                <td>送料</td>
                <td><%= @order.shipping_cost %>円</td>
              </tr>
              <tr>
                <td>請求金額合計</td>
                <td><%= @order.total_payment %>円</td>
              </tr>
            </tbody>
          </table>
        </div>
    </div>
</div>