config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, module: "admins"
  devise_for :customers, module: "customers"

  #以下、public関連のコントローラー/アクション関係設定

  root 'homes#top'
  get 'homes/about' => 'public/homes#about'

  namespace :public do

  resources :items, only: [:index, :show]

  resources :customers, only: [:show, :edit, :update]do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
    end
  end

  resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      post 'confirm'
      get 'complete'
    end
  end

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  #以下、admin関連のコントローラー/アクション設定

  namespace :admin do
  get '/', to: 'homes#top'

  resources :items, only: [:index, :new, :create, :show, :edit, :update]

  resources :genres, only: [:index, :create, :edit, :update]

  resources :customers, only: [:index, :show, :edit, :update]

  get 'admin/orders/:id' =>'orders#show' ,  as: "admin_orders"
  patch 'admin/orders/:id' =>'orders#update'
  patch 'admin/order_details/:id' =>'order_details#update' , as: "admin_order_details"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

 belongs_to :customer

 def full_address
  '〒' + postal_code + ' ' + addresses + ' ' + name
 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders
  
  def active_for_authentication?
    super && (validation == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  attachment :image
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def total price
    ((price * 1.1).floor) * amount
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { unpaid: 0 , paid: 1, making: 2, ready: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { impossible: 0, waiting: 1, making: 2, finish: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

before_action :authenticate_admin!

def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  @genre =Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
    redirect_to admin_genres_path
  else
    render :edit
  end
end

private

def genre_params
  params.require(:genre).permit(:name, :validation)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
    @order_details = OrderDetail.all
    @orders = Order.page(params[:page]).reverse_order.per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :validation)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
    @order_details = OrderDetail.all
    @orders = Order.page(params[:page]).reverse_order.per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.all
  end

  def update
    @orders= Order.find(params[:id])
    @orders.update(order_params)
    redirect_to admin_admin_orders_path
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_customer
      root_path
    else
      admin_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :kata_first_name, :kata_last_name, :email, :postal_code, :address, :telephone_number ])
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: :top

  def top
    @items = Item.page(params[:page]).per(4)
    @genres = Genre.all
  end

def about

end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-offset-3">
      <h4>注文履歴一覧</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-offset-3">
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to admin_admin_orders_path(order.id) do %><%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %><% end %></td>
              <td><%= order.customer.last_name %> <%= order.customer.first_name %></td>
                <% @num =0 %>
              <td>
                <% order.order_details.each do |order_detail| %>
                <% @num += order_detail.amount %>
                <% end %>
                <%= @num %>
              </td>
              <td><%= order.status_i18n %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
		<div class="col-md-6 col-md-offset-4">
			  <div class="mx-auto">
				  <%= paginate @orders %>
			  </div>
		  </div>
	  </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 mr-4">
      <%= render 'layouts/genre_search_sidebar', genres: @genres %>
    </div>
      <div class="col-md-9 col-md-offset-1 m-4">
        <div class="center-block m-5">
          <p class="text-center">ようこそ、ながのCAKEへ！</p>
          <p class="text-center">このサイトは、ケーキ販売のECサイトになります。</p>
          <p class="text-center">会員ではない方も商品の閲覧はできますが、</p>
          <p class="text-center">購入には会員登録が必要になります。</p>
        </div>
      </div>
    </div>
       <div class="row">
         <div class="col-md-2"></div>
          <div class="col-md-10">
            <h2>新着商品</h2>
              <div class="d-flex justify-content-between">
                <% @items.each do |item| %>
                  <%= link_to public_item_path(item.id) do %>
                  <%= attachment_image_tag item, :image, format: 'jpg', class: "pull-left img-responsive", fallback: 'logo.png', size: '180x180' %></br>
                  <%= item.name %></br>
                  <%= item.price %></br>
                  <% end %>
                <% end %>
              </div>
            <div class="nav-links float-right">
              <%= link_to "全ての商品を見る > ", public_items_path %>
            </div>
          </div>
</div>