config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, module: "admins"
  devise_for :customers, module: "customers"

  #以下、public関連のコントローラー/アクション関係設定

  root 'homes#top'
  get 'homes/about' => 'public/homes#about'

  namespace :public do

  resources :items, only: [:index, :show]

  resources :customers, only: [:show, :edit, :update]do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
    end
  end

  resources :cart_items, only: [:index, :update, :destroy, :create] do
    collection do
      delete 'destroy_all'
    end
  end

  resources :orders, only: [:new, :index, :show, :create] do
    collection do
      post 'confirm'
      get 'complete'
    end
  end

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  #以下、admin関連のコントローラー/アクション設定

  namespace :admin do
  get '/', to: 'homes#top'

  resources :items, only: [:index, :new, :create, :show, :edit, :update]

  resources :genres, only: [:index, :create, :edit, :update]

  resources :customers, only: [:index, :show, :edit, :update]

  get 'admin/orders/:id' =>'orders#show' ,  as: "admin_orders"
  patch 'admin/orders/:id' =>'orders#update'
  patch 'admin/order_details/:id' =>'order_details#update' , as: "admin_order_details"

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

 belongs_to :customer

 def full_address
  '〒' + postal_code + ' ' + addresses + ' ' + name
 end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders
  
  def active_for_authentication?
    super && (validation == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  attachment :image
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def total price
    ((price * 1.1).floor) * amount
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer

  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { unpaid: 0 , paid: 1, making: 2, ready: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: { impossible: 0, waiting: 1, making: 2, finish: 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all
    @order_details = OrderDetail.all
    @orders = Order.page(params[:page]).reverse_order.per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :validation)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_customer
      root_path
    else
      admin_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :kata_first_name, :kata_last_name, :email, :postal_code, :address, :telephone_number ])
  end

  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: :top

  def top
    @items = Item.page(params[:page]).per(4)
    @genres = Genre.all
  end

def about

end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_genre_search_sidebar.html.erb
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="active text-center">ジャンル検索</th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre|%>
    <tr>
      <td class="genrename"><%= genre.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand">
        <div class="container">
          <nav class="navbar navbar-light navbar-left">

          <% if request.url.include?('admin')  %>
            <a href="/admin">
              <%= image_tag 'logo.png', size:'300x80' %>
            </a>
              <% else %>
            <a href="/">
              <%= image_tag 'logo.png', size:'300x80' %>
            </a>
            <% end %>
          </nav>

            <ul class="navbar-nav bg-test_text">
              <%#以下、管理者がログインした場合%>
                <% if admin_signed_in? %>
                  <li>
                    <%= link_to " 商品一覧", admin_items_path, class: "nav-link bg-light text-dark header-tab" %>
                  </li>
                  <li>
                    <%= link_to " 会員一覧", admin_customers_path, class: "nav-link bg-light text-dark btn btn-light header-tab" %>
                  </li>
                  <li>
                    <%= link_to " 注文履歴一覧", admin_path, class: "nav-link bg-light text-dark btn btn-light header-tab2" %>
                  </li>
                  <li>
                    <%= link_to " ジャンル一覧", admin_genres_path, class: "nav-link bg-light text-dark btn btn-light header-tab2" %>
                  </li>
                  <li>
                    <%= link_to " ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link bg-light text-dark btn btn-light header-tab"  %>
                  </li>

                  <%#以下、会員がログインした場合%>
                  <% elsif customer_signed_in? %>
                  <li>
                    ようこそ、<%= current_customer.last_name %>さん！
                  </li>
                  <li class="nav-list">
                    <%= link_to " マイページ", public_customer_path(current_customer.id), class: "nav-link bg-light text-dark btn btn-light header-tab" %>
                  </li>
                  <li class="nav-list">
                    <%= link_to " 商品一覧", public_items_path, class: "nav-link bg-light text-dark btn btn-light header-tab" %>
                  </li>
                  <li class="nav-list">
                    <%= link_to " カート", public_cart_items_path, class: "nav-link bg-light text-dark btn btn-light header-tab" %>
                  </li>
                  <li class="nav-list">
                    <%= link_to " ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link bg-light text-dark btn btn-light header-tab" %>
                  </li>

                  <%#以下、管理者/会員がログインしていない場合%>
                  <% else %>
                  <li class="nav-item">
                    <%= link_to " About", homes_about_path, class: "nav-link bg-light text-dark btn btn-light header-tab" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to " 商品一覧", public_items_path, class: "nav-link bg-light text-dark btn btn-light header-tab" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to " 新規登録", new_customer_registration_path, class: "nav-link bg-light text-dark btn btn-light header-tab" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to " ログイン", new_customer_session_path, class: "nav-link bg-light text-dark btn btn-light header-tab" %>
                  </li>
                  <% end %>
                  
            </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>